### ISSUE TITLE
Add CTC decoder builds for more Python versions

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3596]
We hard-coded the action call with one version https://github.com/mozilla/DeepSpeech/blob/5f566f442541d76f320ee081294cdef980c361d1/.github/workflows/macOS-amd64.yml#L54-L86 it would be nice to:
 - use a matrix for all versions we can
 - add new `train-test-model` jobs using a matrix as well to ensure test coverage

**Comment by lissyx** [comment]
@Ayushsunny This might be easier, if you are still willing to learn GitHub Actions at the same time

**Comment by Ayushsunny** [comment]
> @Ayushsunny This might be easier, if you are still willing to learn GitHub Actions at the same time

Omg, Thank you so much as you want me to learn. It's so nice of you Sir @lissyx .
and yes I want to learn, So what I have to do first to understand this specific topic to fix this issue

**Comment by lissyx** [comment]
> So what I have to do first to understand this specific topic to fix this issue

Read this code, get yourself into https://docs.github.com/en/actions/guides :)

**Comment by lissyx** [comment]
@Ayushsunny Have you been able to get a grasp of what needs to be done ?

**Comment by lissyx** [comment]
@Ayushsunny Ping?

**Comment by Ayushsunny** [comment]
I'm really sorry Sir @lissyx 
I was studying for my University Exam.
Now I'm free and from tomorrow I'll start working on it.

**Comment by lissyx** [comment]
> I'm really sorry Sir @lissyx
> I was studying for my University Exam.
> Now I'm free and from tomorrow I'll start working on it.

Thanks, I don't want to pressure you, it's fine if you can't take it, but we just need to know :)

**Comment by Ayushsunny** [comment]
So Sir, as per my understanding I think this should be the code which I have to add. @lissyx ?

``` YML
jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy-2.7', 'pypy-3.6', 'pypy-3.7' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python my_script.py `

**Comment by lissyx** [comment]
@Ayushsunny Sorry looks like my reply got lost ; that's the good basis, you'll have to build on top of that.

**Comment by Ayushsunny** [comment]
> @Ayushsunny Sorry looks like my reply got lost ; that's the good basis, you'll have to build on top of that.

Which reply Sir? @lissyx 
and, may make a PR for this? or I need to improve the last code which I've sent .

**Comment by Ayushsunny** [comment]
> @Ayushsunny Sorry looks like my reply got lost ; that's the good basis, you'll have to build on top of that.

Which reply Sir? @lissyx 
and, may make a PR for this? or I need to improve the last code which I've sent .

**Comment by lissyx** [comment]
> Which reply Sir? @lissyx

One I thought I had sent



>  and, may make a PR for this? or I need to improve the last code which I've sent .

What you shared is not what we need, but it's on the right path. 

We need a job like the one I shared earlier, but on more versions of python.

**Comment by Ayushsunny** [comment]
sir but here you've already used matrix ?https://github.com/lissyx/STT/blob/aed5f187cea0ca343cf3fe4a7278ef98fd0d5561/.github/workflows/macOS-amd64.yml#L59

or maybe I'm not able to understand you, Do I need to build a new CTC-decoder and train-test-model or only make some changes in the code that you've hardcoded? please Sir @lissyx

**Comment by Ayushsunny** [comment]
> > Which reply Sir? @lissyx
> 
> One I thought I had sent
> 
> > and, may make a PR for this? or I need to improve the last code which I've sent .
> 
> What you shared is not what we need, but it's on the right path.
> 
> We need a job like the one I shared earlier, but on more versions of python.

Okay @lissyx Sir I got it do we need like this right ?
```yml
  build-ctc-decoder: 
     name: "Build CTC decoder Python package for testing" 
     needs: [ swig_macOS ] 
     runs-on: macos-10.15 
     strategy:
      matrix:
        python-version: [3.6.8, 3.7.9, 3.8.8, 3.9.2]
     if: ${{ github.event_name == 'pull_request' }} 
     steps: 
       - uses: actions/checkout@v2 
         with: 
           fetch-depth: 0 
       - uses: ./.github/actions/install-python-upstream 
         with: 
           version:  ${{ matrix.python-version }}
       - run: | 
           python --version 
           pip --version 
       - uses: actions/download-artifact@v2 
         with: 
           name: "swig_macOS" 
           path: ${{ github.workspace }}/native_client/ds-swig/ 
       - run: | 
           ls -hal ${{ github.workspace }}/native_client/ds-swig/bin 
           ln -s ds-swig ${{ github.workspace }}/native_client/ds-swig/bin/swig 
           chmod +x ${{ github.workspace }}/native_client/ds-swig/bin/ds-swig ${{ github.workspace }}/native_client/ds-swig/bin/swig 
       - run: | 
           make -C native_client/ctcdecode/ \ 
             NUM_PROCESSES=$(sysctl hw.ncpu |cut -d' ' -f2) \ 
             bindings 
       - uses: actions/upload-artifact@v2 
         with: 
           name: "ds_ctcdecoder-test.whl" 
           path: ${{ github.workspace }}/native_client/ctcdecode/dist/*.whl 
       - run: | 
           make -C native_client/ctcdecode clean-keep-third-party 
```
